// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1NcRNPFYnACwb6PQEhcbZPzyuvo6C9E',
    appId: '1:241332019153:web:431eca1eb3fc261b80caf0',
    messagingSenderId: '241332019153',
    projectId: 'clinic-connect-kenya',
    authDomain: 'clinic-connect-kenya.firebaseapp.com',
    storageBucket: 'clinic-connect-kenya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOgMoijbhbfINxwxh0qI4IR-g8XYLkiPk',
    appId: '1:241332019153:android:c6e2ce14c5af363b80caf0',
    messagingSenderId: '241332019153',
    projectId: 'clinic-connect-kenya',
    storageBucket: 'clinic-connect-kenya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-XEQIrbFNJwDCylKvINQ1YIF-PXjNoho',
    appId: '1:241332019153:ios:0384821611909ad480caf0',
    messagingSenderId: '241332019153',
    projectId: 'clinic-connect-kenya',
    storageBucket: 'clinic-connect-kenya.firebasestorage.app',
    iosBundleId: 'com.example.clinicConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-XEQIrbFNJwDCylKvINQ1YIF-PXjNoho',
    appId: '1:241332019153:ios:0384821611909ad480caf0',
    messagingSenderId: '241332019153',
    projectId: 'clinic-connect-kenya',
    storageBucket: 'clinic-connect-kenya.firebasestorage.app',
    iosBundleId: 'com.example.clinicConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG1NcRNPFYnACwb6PQEhcbZPzyuvo6C9E',
    appId: '1:241332019153:web:195fa852d734232480caf0',
    messagingSenderId: '241332019153',
    projectId: 'clinic-connect-kenya',
    authDomain: 'clinic-connect-kenya.firebaseapp.com',
    storageBucket: 'clinic-connect-kenya.firebasestorage.app',
  );
}
